### ISSUE TITLE
Making a copy of a book page strips ancillaries off original

### ISSUE THREAD

**Issue by lwtchu** [openstax/business-intel#267]
### Description

**SCENARIO** _Briefly describe the issue._

We made a copy of the Chemistry 1e  book for Chemistry 2e and it stripped all of the ancillaries from 1e. Therefore it isn't a copy.

NOTE: If we're not supposed to use this then please take it away.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_
Go to subject page and when you click on more options there's a drop down to select a copy
![Screen Shot 2019-02-15 at 2.17.50 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/a4865fe0-65b8-4450-8f9c-bc8825e56ac6)

- **User Type:**
` [ ] ` Admin  ` [x] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** any CM log in
- **URL:**  openstax.org/admin
- **Course number:**  N/A
- **Course type:**  N/A

- **Steps**
ugh look above
----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
We don't want to reinput the stuff ! also users are missing ancillaries - we only found out cause a user reported it.
----------------
**Images or Screenshots** (_attach below_)

----------------
### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by berkalpyakici** [comment]
This happens because ancillaries like faculty_resources are stored in the following format in page contents: `[{'link_page': None, 'book_faculty_resource': 344, 'link_document': 390, 'sort_order': 0, 'resource': 1, 'pk': 1743, 'link_text': 'Download', 'link_external': ''}, {'link_page': None, 'book_faculty_resource': 344, 'link_document': 790, 'sort_order': 1, 'resource': 44, 'pk': 1744, 'link_text': 'Download', 'link_external': ''}, {'link_page': None, 'book_faculty_resource': 344, 'link_document': 775, 'sort_order': 3, 'resource': 3, 'pk': 1746, 'link_text': 'Download', 'link_external': ''}, {'link_page': None, 'book_faculty_resource': 344, 'link_document': 64, 'sort_order': 4, 'resource': 13, 'pk': 1747, 'link_text': 'Download', 'link_external': ''}, {'link_page': None, 'book_faculty_resource': 344, 'link_document': 650, 'sort_order': 5, 'resource': 8, 'pk': 1748, 'link_text': 'Download', 'link_external': ''}]`, where each record also has a primary key `pk`. While copying, these primary keys are untouched, and hence, the ancillaries on the new page end up sharing the same primary keys as the ones on the old page. This results in ancillaries being moved from one page to another. To resolve this, each `pk` in every single ancillary object must be nullified before the new page is initialized. Until wagtail releases a new patch for this, we will be adding a new menu item for duplicating books.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
