### ISSUE TITLE
Add functionality to Salesforce that will trigger during a refresh

### ISSUE THREAD

**Issue by mwharrison** [openstax/business-intel#344]
@mwharrison commented on [Tue Apr 16 2019](https://github.com/openstax/openstax-cms/issues/749)

- make sure test records are uploaded
- send new OID to Roy 
- modify user email addresses to remove `.invalid` from the end

**Comment by denvergreene** [comment]
I'm going to add a bit so that instead of just sending to Roy's email address, we'll be able to update the to address without updating the code

**Comment by denvergreene** [comment]
One error with duplicate email address remains, but it hopefully will be fixed. If that error doesn't show up then we can test refreshing it again.

**Comment by denvergreene** [comment]
From Malar "usually teacher01 - teacher09 in QA and teacher01 - teacher05 in staging have faculty access...but looks like now teacher 01, teacher02 in QA and teacher 01 in staging alone are having the faculty access"

**Comment by Brooke-Fail** [comment]
After the refresh, the previously requested accounts still had FV. I sent Denver another set of emails to be included. Will verify that new list whenever there is another refresh of sandbox.

**Comment by denvergreene** [comment]
The last couple of refresh tests no one ever changed the ORG id, but everything was still working. So I removed the part that wasn't working with the email to roy, and hopefully it will be fine now.

If we do need to add it in eventually then we can send the org id to developers in slack. 

One more test to run since adding in the most recent things from QA
